language: node_js
node_js:
  - '0.10'
  - '0.12'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'

notifications:
    email:
        recipients:
            - promisejohn@qq.com
        on_success: always
        on_failure: always
